"""人形机器人概念知识包。

节点描述是行业分类，不代表相关公司已形成收入；股票关联均使用审慎措辞并附来源。
"""

ROOT_SOURCE = {"title": "人形机器人创新发展指导意见", "url": "https://www.miit.gov.cn/zwgk/zcwj/wjfb/tz/art/2023/art_4b7f31fb4ced487c9d08c0b1a3ab36a8.html", "publisher": "工业和信息化部"}

NODES = [
    ("robotics", None, "机器人", "domain", "融合机械、感知、控制与人工智能的复杂系统。", None),
    ("robotics/body", "robotics", "本体与系统集成", "segment", "整机设计、制造、集成和交付。", "midstream"),
    ("robotics/body/humanoid", "robotics/body", "人形机器人", "product", "采用类人形态完成通用操作与移动任务。", "downstream"),
    ("robotics/body/industrial", "robotics/body", "工业机器人", "product", "面向焊接、装配、搬运等工业任务。", "downstream"),
    ("robotics/body/cobot", "robotics/body", "协作机器人", "product", "强调人机协作、安全和易部署。", "downstream"),
    ("robotics/body/mobile", "robotics/body", "移动机器人", "product", "以自主导航和移动作业为核心。", "downstream"),
    ("robotics/execution", "robotics", "执行系统", "segment", "将控制指令转换为关节和末端动作。", "midstream"),
    ("robotics/execution/joint", "robotics/execution", "关节模组", "component", "集成电机、减速器、编码器与驱动器。", "midstream"),
    ("robotics/execution/joint/rotary", "robotics/execution/joint", "旋转关节", "component", "输出旋转运动的关节方案。", "midstream"),
    ("robotics/execution/joint/linear", "robotics/execution/joint", "直线关节", "component", "通过丝杠等机构输出直线运动。", "midstream"),
    ("robotics/execution/hand", "robotics/execution", "灵巧手", "component", "多自由度末端执行器，用于抓取和精细操作。", "midstream"),
    ("robotics/execution/hand/drive", "robotics/execution/hand", "驱动", "technology", "为手指关节提供动力。", "upstream"),
    ("robotics/execution/hand/drive/coreless", "robotics/execution/hand/drive", "空心杯电机", "component", "转动惯量低，适合小型高响应执行机构。", "upstream"),
    ("robotics/execution/hand/drive/brushless", "robotics/execution/hand/drive", "无刷电机", "component", "高效率、长寿命的微型驱动方案。", "upstream"),
    ("robotics/execution/hand/transmission", "robotics/execution/hand", "传动", "technology", "将动力传至手指并匹配速度和力矩。", "upstream"),
    ("robotics/execution/hand/transmission/screw", "robotics/execution/hand/transmission", "微型丝杠", "component", "将旋转运动转换为精密直线运动。", "upstream"),
    ("robotics/execution/hand/transmission/tendon", "robotics/execution/hand/transmission", "腱绳传动", "technology", "以绳索模拟肌腱传力，利于轻量化。", "upstream"),
    ("robotics/execution/hand/sensing", "robotics/execution/hand", "传感", "technology", "为抓取闭环提供力、位置和接触信息。", "upstream"),
    ("robotics/execution/hand/sensing/force", "robotics/execution/hand/sensing", "力与力矩传感", "component", "测量交互力与关节力矩。", "upstream"),
    ("robotics/execution/hand/sensing/tactile", "robotics/execution/hand/sensing", "触觉传感", "component", "感知接触位置、压力与纹理。", "upstream"),
    ("robotics/execution/hand/sensing/e-skin", "robotics/execution/hand/sensing/tactile", "电子皮肤", "technology", "大面积柔性触觉阵列，可覆盖机器人表面。", "upstream"),
    ("robotics/execution/hand/sensing/e-skin/substrate", "robotics/execution/hand/sensing/e-skin", "柔性基材", "material", "承载可弯折传感单元与互连结构。", "upstream"),
    ("robotics/execution/hand/sensing/e-skin/conductive", "robotics/execution/hand/sensing/e-skin", "导电材料", "material", "构成柔性电极和敏感层。", "upstream"),
    ("robotics/execution/hand/sensing/e-skin/routes", "robotics/execution/hand/sensing/e-skin", "压阻、电容与压电方案", "technology", "电子皮肤常见的信号转换路线。", "upstream"),
    ("robotics/execution/reducer", "robotics/execution", "减速器", "component", "降低转速并放大力矩。", "upstream"),
    ("robotics/execution/reducer/harmonic", "robotics/execution/reducer", "谐波减速器", "component", "体积小、减速比高，常用于轻载关节。", "upstream"),
    ("robotics/execution/reducer/rv", "robotics/execution/reducer", "RV减速器", "component", "刚度和承载能力较高，常用于重载关节。", "upstream"),
    ("robotics/execution/screw", "robotics/execution", "丝杠", "component", "旋转与直线运动转换部件。", "upstream"),
    ("robotics/execution/screw/ball", "robotics/execution/screw", "滚珠丝杠", "component", "以滚珠降低摩擦的精密传动部件。", "upstream"),
    ("robotics/execution/screw/roller", "robotics/execution/screw", "行星滚柱丝杠", "component", "高承载密度的直线执行方案。", "upstream"),
    ("robotics/execution/motor", "robotics/execution", "电机", "component", "机器人执行系统的动力源。", "upstream"),
    ("robotics/execution/motor/servo", "robotics/execution/motor", "伺服电机", "component", "实现位置、速度和力矩闭环控制。", "upstream"),
    ("robotics/execution/motor/frameless", "robotics/execution/motor", "无框力矩电机", "component", "便于与关节结构高度集成。", "upstream"),
    ("robotics/perception", "robotics", "感知系统", "segment", "获取环境、姿态与交互状态。", "upstream"),
    ("robotics/perception/vision", "robotics/perception", "机器视觉", "technology", "基于图像完成识别、定位和测量。", "upstream"),
    ("robotics/perception/3d", "robotics/perception", "3D视觉", "technology", "获取深度和三维空间信息。", "upstream"),
    ("robotics/perception/lidar", "robotics/perception", "激光雷达", "component", "用于测距、建图和避障。", "upstream"),
    ("robotics/perception/imu", "robotics/perception", "IMU", "component", "测量角速度与加速度。", "upstream"),
    ("robotics/perception/encoder", "robotics/perception", "编码器", "component", "反馈关节位置和速度。", "upstream"),
    ("robotics/perception/six-axis", "robotics/perception", "六维力传感器", "component", "同步测量三轴力和三轴力矩。", "upstream"),
    ("robotics/control", "robotics", "控制与计算", "segment", "负责运动规划、实时控制与智能决策。", "midstream"),
    ("robotics/control/motion", "robotics/control", "运动控制器", "component", "生成多轴协同运动指令。", "midstream"),
    ("robotics/control/servo", "robotics/control", "伺服驱动", "component", "驱动电机并闭环控制。", "midstream"),
    ("robotics/control/edge", "robotics/control", "AI芯片与边缘计算", "technology", "提供本地感知和推理算力。", "midstream"),
    ("robotics/control/embodied-ai", "robotics/control", "大模型与具身智能", "technology", "将多模态理解、规划和动作生成连接起来。", "midstream"),
    ("robotics/materials", "robotics", "能源与材料", "segment", "支撑续航、轻量化和可靠连接。", "upstream"),
    ("robotics/materials/battery", "robotics/materials", "电池", "component", "移动机器人主要能源系统。", "upstream"),
    ("robotics/materials/lightweight", "robotics/materials", "轻量化材料", "material", "降低整机质量和执行能耗。", "upstream"),
    ("robotics/materials/harness", "robotics/materials", "线束与连接器", "component", "传输电力、控制和传感信号。", "upstream"),
    ("robotics/applications", "robotics", "应用场景", "segment", "机器人商业化落地的需求端。", "downstream"),
    ("robotics/applications/auto", "robotics/applications", "汽车制造", "application", "焊装、总装、检测和物流。", "downstream"),
    ("robotics/applications/3c", "robotics/applications", "3C电子", "application", "精密装配、检测与搬运。", "downstream"),
    ("robotics/applications/logistics", "robotics/applications", "物流仓储", "application", "分拣、搬运和仓内作业。", "downstream"),
    ("robotics/applications/medical", "robotics/applications", "医疗康复", "application", "手术辅助、康复训练和护理。", "downstream"),
    ("robotics/applications/home", "robotics/applications", "家庭服务", "application", "清洁、陪护和通用家务。", "downstream"),
]

STOCK_LINKS = [
    ("robotics/execution/hand/sensing/e-skin", "605488", "材料与器件布局", "公司公开信息涉及柔性传感器及电子皮肤方向，属于潜在触觉感知材料链路；不代表已形成规模收入。", 0.88, True, "https://www.fulai.com.cn/"),
    ("robotics/perception/six-axis", "603662", "力传感器", "公司主营称重与力学测量，并公开布局机器人力传感相关产品。", 0.88, True, "https://www.kelichina.com/"),
    ("robotics/execution/hand/sensing/tactile", "300007", "柔性传感", "公司传感器业务覆盖多类感知器件，公开信息涉及柔性压力传感方向。", 0.75, False, "https://www.hanwei.cn/"),
    ("robotics/perception/3d", "688322", "3D视觉", "公司以3D视觉感知技术和产品为核心业务。", 0.96, True, "https://www.orbbec.com.cn/"),
    ("robotics/execution/reducer/harmonic", "688017", "谐波减速器", "公司主营精密传动装置，谐波减速器用于机器人关节。", 0.98, True, "https://www.leaderdrive.com/"),
    ("robotics/execution/hand/drive/coreless", "603728", "微型驱动", "公司运动控制业务覆盖步进、无刷及空心杯等微型驱动产品。", 0.91, True, "https://www.moons.com.cn/"),
    ("robotics/control/servo", "300124", "伺服与控制", "公司工业自动化业务覆盖伺服系统、控制器等机器人核心控制环节。", 0.92, True, "https://www.inovance.com/"),
    ("robotics/control/motion", "002979", "运动控制", "公司主营运动控制核心部件，包括控制器、伺服和步进系统。", 0.93, True, "https://www.leisai.com/"),
    ("robotics/body/industrial", "002747", "机器人本体", "公司业务覆盖工业机器人本体、核心部件及智能制造系统。", 0.95, True, "https://www.estun.com/"),
    ("robotics/body/industrial", "300024", "机器人本体", "公司长期从事工业机器人、移动机器人及自动化系统业务。", 0.95, True, "https://www.siasun.com/"),
    ("robotics/body/industrial", "300607", "机器人本体与集成", "公司业务覆盖工业机器人、注塑自动化及智能工厂系统。", 0.88, False, "https://www.topstarltd.com/"),
    ("robotics/body/industrial", "688165", "机器人本体与集成", "公司主营工业机器人整机和系统集成。", 0.93, True, "https://www.efort.com.cn/"),
    ("robotics/body", "688097", "系统集成", "公司智能制造装备业务包含自动化产线和机器人系统集成。", 0.82, False, "https://www.bozhon.com/"),
    ("robotics/execution/reducer", "002896", "精密传动", "公司产品覆盖减速器及机电一体化传动部件。", 0.87, True, "https://www.zd-motor.com/"),
    ("robotics/execution/joint", "002050", "执行器部件", "公司热管理和执行器相关产品被市场关注于机器人机电执行环节，实际进展以公司公告为准。", 0.72, False, "https://www.sanhuagroup.com/"),
]

